# SwiftLint Configuration for Photo Metadata Editor

included:
  - Photo Metadata Editor
  - Photo Metadata EditorTests
  - Photo Metadata EditorUITests

excluded:
  - .build
  - DerivedData
  - Pods

# Rule configuration
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - first_where
  - force_unwrapping
  - implicit_return
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

disabled_rules:
  - trailing_whitespace
  - line_length

# Customizations
force_cast: warning
force_try: warning
force_unwrapping: warning

identifier_name:
  min_length: 1
  max_length: 60
  excluded:
    - id
    - x
    - y
    - i
    - j
    - ok

type_name:
  min_length: 3
  max_length: 50

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

reporter: xcode
